// Personajes
export const ADD_CHARACTER_COMPLETED = 'objects/ADD_CHARACTER_COMPLETED';
export const MODIFY_CHARACTER_COMPLETED = 'objects/MODIFY_CHARACTER_COMPLETED';
export const DELETE_CHARACTER_COMPLETED = 'objects/DELETE_CHARACTER_COMPLETED';
export const FIND_CHARACTERS_COMPLETED = 'objects/FIND_CHARACTERS_COMPLETED';
export const CLEAR_CHARACTERS_SEARCH = 'objects/CLEAR_CHARACTERS_SEARCH';