spring.application.name=truby-writer

app.projects.root-path=C:/TrubyWriter/Projects/

spring.datasource.url=jdbc:h2:file:./data/midb;AUTO_SERVER=TRUE

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
server.port=8081